name: finanz_app
description: "FinanzApp te ayuda a llevar un control claro y visual de tus ingresos, gastos fijos y gastos hormiga. Navega entre las pestañas para ver tu balance diario, gestionar tu presupuesto fijo, analizar tus gastos y consultar resúmenes mensuales o anuales."

# Previene que se publique accidentalmente en pub.dev
publish_to: 'none'

# Versión de la app
version: 1.0.0+1

# Compatibilidad con Dart
environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencias principales del proyecto
dependencies:
  flutter:
    sdk: flutter

  # UI y diseño
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0

  # Publicidad
  google_mobile_ads: ^6.0.0

  # Persistencia local
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

  # Estado y utilidades
  provider: ^6.1.1
  uuid: ^4.3.3
  intl: ^0.19.0

  # Nuevas dependencias
  url_launcher: ^6.2.5
  
  # Exportación de datos
  csv: ^5.1.1
  share_plus: ^7.2.1

  # Nuevo archivo
  file_picker: ^10.1.9

# Dependencias de desarrollo (solo en desarrollo, no producción)
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

# Configuración del generador de íconos
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

# Configuraciones específicas de Flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
